### ISSUE TITLE
 ImportError: cannot import name ABC

### ISSUE THREAD

**Issue by b-delfino** [junyanz/pytorch-CycleGAN-and-pix2pix#1091]
Hi, I am trying to run the pretained pix2pix on facades. When running this: 

python test.py --dataroot ./datasets/facades/ --direction BtoA --model pix2pix --name facades_label2photo_pretrained

I get the following error: ImportError: cannot import name ABC

I am working on ubuntu 18 with python 3.6.9

(I already saw a similar thread but I am not using docker so their fixes didn't work) Thank you!

**Comment by junyanz** [comment]
The ImportError `cannot import name ABC` might be caused by the Python version. I am using Python 3.7.6.

**Comment by b-delfino** [comment]
yes, for anyone who has the same problem running it with python3 instead of python worked. 

python3 test.py --dataroot ./datasets/facades/ --direction BtoA --model pix2pix --name facades_label2photo_pretrained
