### ISSUE TITLE
AttributeError: 'module' object has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by elenoka** [junyanz/pytorch-CycleGAN-and-pix2pix#267]
Hello! 
I got an Error 'AttributeError: 'module' object has no attribute '_cuda_setDevice'' when run instruction ''sudo bash ./scripts/train_cyclegan.sh''
I have installed CUDA 8.0 and it works fine on other deep learning framework such as caffe. 
Can anyone help me to solve this problem please?
Thank you very much! 

===detail information on linux===

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    opt = TrainOptions().parse()
  File "/home/tyj/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 63, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/usr/local/python-2.7.9/lib/python2.7/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: 'module' object has no attribute '_cuda_setDevice'

===details end====

Problem solved! It seems that I am using the wrong version of pytorch, I reinstalled pytorch 0.3.1 and it worked. Thank you all.

**Comment by junyanz** [comment]
Cool. The current version only works with PyTorch <=0.3.1. We will make it compatible with PyTorch 0.4 soon.
